### ISSUE TITLE
Wallet - Public Address is different from the "Created Account" address

### ISSUE THREAD

**Issue by michele00p** [bosnet/web-wallet#2]
**Description**

When an user creates a new account, the Public Address (GBCX3P4VK7E2OJHWMPTN6GAU3N2GHDYJPTI76ZHKFIKGRUQ7KRG2FOQ5) displayed is different from the "Created Account" address (GCCR35A2IWCPWZVIBKHDDM4IXW3EKY6NPPS3RG2XOTHAQKC6EJW4U2N6) reported in the account history.

Sending tokens from my account to another one, the receiver will get the tokens from GBCX3P4VK7E2OJHWMPTN6GAU3N2GHDYJPTI76ZHKFIKGRUQ7KRG2FOQ5, so the "Created Account" address could be the one displayed incorrectly.

![schermata 2018-11-20 alle 14 29 12](https://user-images.githubusercontent.com/45069772/48777070-dc1ce000-ecd1-11e8-9564-6805e6cb0381.png)

**Comment by michele00p** [comment]
Hi @moonKim-ermind , can you please give me a feedback about this issue? Is it a real issue and will it be fixed before MainNet launch?

**Comment by moonKim-ermind** [comment]
Hi @michele00p.
Public Address in the account history is Sender's Public Address If label is 'Created Account' or 'Receive'.
So Public Address in Created Account is different from Receiver(new account)'s Address.

That history says GCCR35A2IWCPWZVIBKHDDM4IXW3EKY6NPPS3RG2XOTHAQKC6EJW4U2N6 give 10 BOS to GBCX3P4VK7E2OJHWMPTN6GAU3N2GHDYJPTI76ZHKFIKGRUQ7KRG2FOQ5. and GBCX3P4VK7E2OJHWMPTN6GAU3N2GHDYJPTI76ZHKFIKGRUQ7KRG2FOQ5 is Created.

So That is correct

**Comment by michele00p** [comment]
Thanks for your quick answer, @moonKim-ermind .

If I understood well, it is just a behaviour of TestNet because we won't have these 10 BOS for a new account creation in MainNet, right?

**Comment by moonKim-ermind** [comment]
Yes. If you create new account. the new account have only publicAddress-SecretSeed pair, and not Valid.
like 'Key generator' button

If user click 'Create new account on Testnet', Angelbot give 10 BOS to new Account for test Send, Receive and other features.

**Comment by michele00p** [comment]
Thank you again for your clear explanation.

I'm going to close this issue.
